### ISSUE TITLE
Use all the configurations

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#45]
http://jekyllrb.com/docs/configuration/

Someone should probably go through this list and see if we can turn on any cool features.

**Comment by bhuvan-venkatesh** [comment]
* `include: [DIR, FILE, ...]` We should probably start white listing directories instead of having jekyll copy all non-standard directories verbatim
* `encoding: ENCODING` Just so we have a standard encoding
* `lsi: BOOL` "Latent Sentiment Analysis" is really cool but we are going to optimize it if we were to use it. It essentially analyzes post content and sees if there are enough semantic links between them and builds an index (like grouping assignments). idk.
* Webbrick headers
```
# File: _config.yml
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
```
We should to set content-type and cache control for more caching, that or move all of our script tags in the head to the body or start using requirejs to get dependencies loaded asynchronously.

* Hardcode defaults so we always know what they are http://jekyllrb.com/docs/configuration/#default-configuration.
* http://jekyllrb.com/docs/configuration/#liquid-options, Change any warning settings? We are systems programmers -- we should be listening to warnings.

**Comment by bhuvy2** [comment]
Liquid sucks, anything we need extra in terms of features we can now do with travis.
