### ISSUE TITLE
Better define what is cheating

### ISSUE THREAD

**Issue by bchong95** [illinois-cs241/illinois-cs241.github.io#70]
I think Jeffe does this best:

https://courses.engr.illinois.edu/cs473/integrity.html

**Comment by angrave** [comment]
Suggest you link to it but note the following differences-

1) Rather than a zero in assignment, the sanction for plagiarism (or 
aiding another student) is to reduce grade by one whole letter.

2) Cheating at a CBTF digital exam is taken very seriously and may 
result in a failure of the whole course.

**Comment by bhuvy2** [comment]
Done
