### ISSUE TITLE
Refactor to get rid of jekyll

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/illinois-cs241.github.io#89]
Jekyll sucks. Ideally, we move to a python based parser like https://github.com/lepture/mistune and `jinja` templates so we can generate the files ourself.

Pros:
    - All python-y extensions are available to us
    - More maintainability!
    - Get rid of the ruby plugins
    - We already have travis, so we just need to change a couple of lines in the build, and it'll work.
Cons:
    - Jekyll had a few good features for us, can't really think of it
    - Nothing else, jekyll sucked to develop with

**Comment by earwig** [comment]
What's wrong with Jekyll, really?

**Comment by bhuvy2** [comment]
So my problem with jekyll is that currently
* The table of contents is generated by feeding the entire doc through a jekyll filter
* You have to define your templates inside your code (i.e. nokogiri wrapping divs is defined in the code). This is already a solved problem, you can have a jinja template with special variables `title` `content_blocks` and iterate through those content blocks (or ruby for that matter)
* We can have more resolute pathing
* Since the system is in python, we can have a minimal amount of maintainable code to do things like readability, grammar checking, and accessibility checking on build (jekyll can output stuff, but can't send an email with errors).
* I'm also the only one significantly maintaining this; I believe more people would help if the build was in python and in code we wrote

We do lose some of the benefits, like their updates, but we've already been bitten by this dependency before during manual deploys)

**Comment by angrave** [comment]
I wont stop you  but honestly I'm unconvinced. Here's why.

 I'm dubious about the value of writing code to replace Jekyll. You also loose documentation and replace it with new code that now needs to be maintained (and since it is new will have bugs).Jekyll does what it does well and is relatively simple to understand. 

TOC via a jekyll filter = that seems a reasonable  process to me. [OK You could also preprocess this if you really wanted to (and still use jekyll)]. BTW a Jekyll filter exists to create site maps.
https://support.google.com/webmasters/answer/156184?hl=en

Re. templates. Are you sure that no jekyll plugin exists to do this??
Again I'd much rather see micro bits of code being written (e.g.  Jekyll plugins) than ripping out a mature open source solution with some homegrown undocumented solution.

If you run jekyll locally it will spit out errors as you build (or automatically build due saving a file).

"More resolute pathing." Not sure what this means. I expect this is already a solved problem with Jekyll site variables and variable substituition.

**Comment by bhuvy2** [comment]
Closing, I've overcome most of the above problems with more generators. We'll just have to writing more ruby.
